modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
modId="kingdomswar"
version="${file.jarVersion}"
displayName="Kingdoms War"
authors="vladisss"
description='''
Kingdom warfare mod with AI kingdoms, guards, and territorial conflicts.
'''

[[dependencies.kingdomswar]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.kingdomswar]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"
